version: '3'
env:
  VERSION: 1.0.0-BETA.3
  CGO_ENABLED: "1"

tasks:
  build:
    cmds:
      - go build -gcflags="-m" -buildmode=pie -ldflags "-X main.Version=$VERSION -X main.Build={{.GIT_COMMIT}} -w -s"
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
  
  test:
    cmds:
      - go test -v
  
  fuzz:
    cmds:
      # workaround with ld_cla needed on MacOS due to a bug in Apples new linker: https://github.com/golang/go/issues/65169
      # update 2024-05-15: With the latest MacOS update 14.5 the legacy linker is not available anymore
      #- go test -fuzz=Fuzz -test.fuzztime 10s -ldflags=-extldflags=-Wl,-ld_cla
      - go test -fuzz=Fuzz -test.fuzztime 10s
