version: '3'

dotenv: ['cmd/ftrove/.yara_env']

vars:
  VERSION:
    sh: cat VERSION

env:
  CGO_ENABLED: "1"

includes:
  yara: ./Taskfile.yara.yml
  ftrove:
    taskfile: ./cmd/ftrove/Taskfile.yml
    dir: ./cmd/ftrove
  admftrove:
    taskfile: ./cmd/admftrove/Taskfile.yml
    dir: ./cmd/admftrove
  pkg: ./Taskfile.package.yml

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build all binaries (both dynamic and static)
    deps: [setup-yara-capi]
    cmds:
      - task: ftrove:build
      - task: admftrove:build
    sources:
      - '**/*.go'

  ftrove:
    desc: Build ftrove binaries
    cmds:
      - task: ftrove:build

  admftrove:
    desc: Build admftrove binaries
    cmds:
      - task: admftrove:build

  setup-yara-capi:
    desc: Build and install the YARA-X C library system-wide
    cmds:
      - task: yara:setup-capi

  test:
    desc: Run all library tests
    deps: [setup-yara-capi]
    cmds:
      - go test -v
    sources:
      - '**/*.go'

  fuzz:
    desc: Run fuzz tests for 10 seconds
    deps: [setup-yara-capi]
    cmds:
      # workaround with ld_cla needed on MacOS due to a bug in Apples new linker: https://github.com/golang/go/issues/65169
      # update 2024-05-15: With the latest MacOS update 14.5 the legacy linker is not available anymore
      - go test -fuzz=Fuzz -test.fuzztime 10s

  package:
    desc: Build .deb and .rpm packages (builds binaries first)
    deps: [build]
    cmds:
      - task: pkg:stage
      - task: pkg:deb
      - task: pkg:rpm

  package-deb:
    desc: Build .deb package (builds binaries first)
    deps: [build]
    cmds:
      - task: pkg:stage
      - task: pkg:deb

  package-rpm:
    desc: Build .rpm package (builds binaries first)
    deps: [build]
    cmds:
      - task: pkg:stage
      - task: pkg:rpm

  clean:
    desc: Clean everything
    cmds:
      - task: ftrove:clean
      - task: admftrove:clean
      - go clean
      - rm -rf dist/
