version: '3'

vars:
  VERSION: 1.0.0-BETA-4

env:
  CGO_ENABLED: "1"

includes:
  yara: ./Taskfile.yara.yml
  ftrove:
    taskfile: ./cmd/ftrove/Taskfile.yml
    dir: ./cmd/ftrove
  admftrove:
    taskfile: ./cmd/admftrove/Taskfile.yml
    dir: ./cmd/admftrove

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build all binaries and check that the library package compiles
    deps: [setup-yara-capi]
    cmds:
      - go build ./...
      - task: ftrove:build
      - task: admftrove:build
    sources:
      - '**/*.go'

  setup-yara-capi:
    desc: Build and install the YARA-X C library system-wide
    cmds:
      - task: yara:setup-capi

  test:
    desc: Run all library tests
    deps: [setup-yara-capi]
    cmds:
      - go test -v
    sources:
      - '**/*.go'

  fuzz:
    desc: Run fuzz tests for 10 seconds
    deps: [setup-yara-capi]
    cmds:
      - go test -fuzz=Fuzz -test.fuzztime 10s

  clean:
    desc: Clean everything
    cmds:
      - task: ftrove:clean
      - task: admftrove:clean
      - go clean
