version: '3'
env:
  VERSION: 1.0.0-BETA-4
  CGO_ENABLED: "1"

tasks:
  build:
    cmds:
      - go build -gcflags="-m" -buildmode=pie -ldflags "-X main.Version=$VERSION -X main.Build={{.GIT_COMMIT}} -w -s"
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h

  changetest:
    cmds:
      - go test -v ../../
      - task: build
      - ./ftrove --install .
      - ./ftrove -i ../../testdata -d ../../testdata/dublincore_ex.json -e -p "testing a change. full test." -z "Europe/Berlin"
      - ./ftrove -l
      - sqlite3 db/filetrove.db "select * from files;" ".exit"
      - sqlite3 db/filetrove.db "select * from directories;" ".exit"
      - task: clean

  build_linux_amd:
    cmds:
      - go build -buildmode=pie -ldflags "-X main.Version=$VERSION -X main.Build={{.GIT_COMMIT}} -w -s"
    env:
      GOOS: "linux"
      GOARCH: "amd64"
      CC: "zig cc -target x86_64-linux-musl"
      CXX: "zig cc -target x85_64-linux-musl"


  build_windows_amd:
    cmds:
      - go build -buildmode=pie -ldflags "-X main.Version=$VERSION -X main.Build={{.GIT_COMMIT}} -w -s"
    env:
      GOOS: "windows"
      GOARCH: "amd64"
      CC: "zig cc -target x86_64-windows-musl"
      CXX: "zig cc -target x85_64-windows-musl"


  clean:
    desc: delete builds and testfiles
    cmds:
      - rm -rf ftrove
      - rm -rf ftrove_*
      - rm -rf logs
      - rm -rf dist
      - rm -rf *.tsv
      - mv db/nsrl.db .
      - rm -rf db
