name: buildstatus

on:
  push:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'database_schema.dbml'
      - 'workflows'
      - 'SECURITY.md'
    branches:
      - main

permissions:
  contents: read

jobs:
  xgo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - 
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Build
        uses: crazy-max/ghaction-xgo@de82f877ff4552f03b66c146f608233849e9c3dc # v4.0.0
        with:
          xgo_version: latest
          go_version: 1.21
          dest: build
          prefix: ftrove
          targets: windows/amd64,linux/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          pkg: ./cmd/ftrove
