name: Windows - x86_64 Build YARA-X C API and Go Binary

on:
  workflow_dispatch:  # Enable manual triggering

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache Rust build
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-c
        run: if (-not (Get-Command cargo-cinstall -ErrorAction SilentlyContinue)) { cargo install cargo-c }

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.26.1'

      - name: Install Task
        uses: go-task/setup-task@0ab1b2a65bc55236a3bc64cde78f80e20e8885c2 # v1
        with:
          version: "3.x"

      - name: Cache Go modules
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Clone YARA-X repository
        run: git clone https://github.com/VirusTotal/yara-x.git

      - name: Build YARA-X C API
        run: |
          cd yara-x
          git checkout tags/v1.14.0
          rustup target add x86_64-pc-windows-gnu
          cargo cinstall -p yara-x-capi --release --target=x86_64-pc-windows-gnu --destdir=$env:USERPROFILE\yara_install
          $PC_FILE = Get-ChildItem -Recurse -Filter "yara_x_capi.pc" $env:USERPROFILE\yara_install
          if (-not $PC_FILE) {
            Write-Error "Error: yara_x_capi.pc not found"
            exit 1
          }
          $PC_DIR = Split-Path $PC_FILE.FullName
          Write-Host "Found yara_x_capi.pc in $PC_DIR"
          Get-ChildItem $PC_DIR

      - name: Set environment variables for pkg-config and Go
        run: |
          $pkgConfigPath = "$env:USERPROFILE\yara_install\lib\pkgconfig"
          $cgoCflags = "-I$env:USERPROFILE\yara_install\include"
          $cgoldflags = "-L$env:USERPROFILE\yara_install\lib"
          echo "PKG_CONFIG_PATH=$pkgConfigPath" >> $env:GITHUB_ENV
          echo "CGO_CFLAGS=$cgoCflags" >> $env:GITHUB_ENV
          echo "CGO_LDFLAGS=$cgoldflags" >> $env:GITHUB_ENV
          $env:PKG_CONFIG_PATH = $pkgConfigPath
          pkg-config --cflags --libs yara_x_capi

      - name: Build Go Binary
        run: |
          cd $env:GITHUB_WORKSPACE\cmd\ftrove
          task build

      - name: Create artifacts directory
        run: New-Item -ItemType Directory -Force -Path $env:GITHUB_WORKSPACE\artifacts

      - name: Find dll
        run: |
          Get-ChildItem -Path "$env:USERPROFILE" -Recurse -Filter "yara_x_capi*"

      - name: Copy artifacts
        run: |
          $dllFile = Get-ChildItem -Path "$env:USERPROFILE\yara_install\bin" -Recurse -Filter "yara_x_capi.dll" | Select-Object -First 1
          if (-not $dllFile) {
            Write-Error "DLL file not found in yara_install directory!"
            exit 1
          }
          $dllAFile = Get-ChildItem -Path "$env:USERPROFILE\yara_install\lib" -Recurse -Filter "yara_x_capi.dll.a" | Select-Object -First 1
          if (-not $dllAFile) {
            Write-Error "DLL object file not found in yara_install directory!"
            exit 1
          }
          Copy-Item -Path $dllFile.FullName -Destination "$env:GITHUB_WORKSPACE\artifacts"
          Copy-Item -Path $dllAFile.FullName -Destination "$env:GITHUB_WORKSPACE\artifacts"
          Copy-Item "$env:GITHUB_WORKSPACE\cmd\ftrove\ftrove.exe" -Destination "$env:GITHUB_WORKSPACE\artifacts"

      - name: Create archive of artifacts
        run: |
          Compress-Archive -Path "$env:GITHUB_WORKSPACE\artifacts\*" -DestinationPath "$env:GITHUB_WORKSPACE\windows_x86_64_artifacts.zip"
          if (!(Test-Path -Path "$env:GITHUB_WORKSPACE\windows_x86_64_artifacts.zip")) {
            Write-Error "ZIP archive not found!"
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: build-artifacts
          path: ${{ github.workspace }}\windows_x86_64_artifacts.zip
