name: buildstatus

on:
  push:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'database_schema.dbml'
      - 'workflows'
      - 'SECURITY.md'
    branches:
      - main

permissions:
  contents: read

jobs:
  xgo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      -
        name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - 
        uses: actions/cache@5a3ec84 # v4.2.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Build
        uses: crazy-max/ghaction-xgo@682253ce1d3dd7a78c5120c703c9f3811dbf8cb2 # v3.0.0
        with:
          xgo_version: latest
          go_version: 1.21
          dest: build
          prefix: ftrove
          targets: windows/amd64,linux/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          pkg: ./cmd/ftrove
