name: Debian - x86_64 Build YARA-X C API and Go Binary

on:
  workflow_dispatch:  # Enable manual triggering

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install taskdev
        run: sudo snap install task --classic

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      # Cache Rust build
      - name: Cache Rust build
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-c
        run: cargo install cargo-c

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: '1.23.1'  # Use the desired Go version

      - name: Clone YARA-X repository
        run: git clone https://github.com/VirusTotal/yara-x.git

      - name: Build YARA-X C API and locate .pc file
        run: |
          cd yara-x
          git checkout tags/v0.12.0
          cargo cinstall -p yara-x-capi --release --destdir=$HOME/yara_install
          # Find the .pc file location
          PC_FILE=$(find $HOME/yara_install -name yara_x_capi.pc)
          if [ -z "$PC_FILE" ]; then
            echo "Error: yara_x_capi.pc not found"
            exit 1
          fi
          PC_DIR=$(dirname $PC_FILE)
          echo "Found yara_x_capi.pc in $PC_DIR"
          export PKG_CONFIG_PATH=$PC_DIR
          # Debug output to verify files are correctly installed
          ls -l $PC_DIR

      - name: Clone FileTrove repository
        run: git clone https://github.com/steffenfritz/FileTrove.git

      - name: Set environment variables for pkg-config and Go
        run: |
          export PKG_CONFIG_PATH=/home/runner/yara_install/usr/local/lib/x86_64-linux-gnu/pkgconfig
          export CGO_CFLAGS="-I$HOME/yara_install/usr/local/include"
          export CGO_LDFLAGS="-L$HOME/yara_install/usr/local/lib/x86_64-linux-gnu"
          # Verify pkg-config can find the yara_x_capi package
          pkg-config --cflags --libs yara_x_capi

      - name: Build Go Binary
        run: |
          export PKG_CONFIG_PATH=/home/runner/yara_install/usr/local/lib/x86_64-linux-gnu/pkgconfig
          export CGO_CFLAGS="-I$HOME/yara_install/usr/local/include"
          export CGO_LDFLAGS="-L$HOME/yara_install/usr/local/lib/x86_64-linux-gnu"
          cd FileTrove/cmd/ftrove
          task build

      - name: Create artifacts directory
        run: mkdir -p ../artifacts

      - name: Copy artifacts
        run: |
          cp $HOME/yara_install/usr/local/lib/x86_64-linux-gnu/libyara_x_capi* ../artifacts/
          cp /home/runner/work/FileTrove/FileTrove/FileTrove/cmd/ftrove/ftrove ../artifacts/

      - name: Create archive of artifacts
        run: |
          cd ../artifacts
          tar -czvf ubuntu_x86_64_artifacts.tar.gz *

      - name: Upload artifacts
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: build-artifacts
          path: /home/runner/work/FileTrove/artifacts/ubuntu_x86_64_artifacts.tar.gz

